global:
  scrape_interval: 5s
  scrape_timeout: 1s
  evaluation_interval: 15s

scrape_configs:
- job_name: bench
  metrics_path: '/debug/metrics/prometheus'
  file_sd_configs:
    - files:
      - ./prom_end.json
